import { useEffect, useState, useRef } from "react";
import styles from "@/styles/artists/ZecaIcaris.module.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import ReleasesSection from "@/components/ReleasesSection"; // Import the new component
import ScrollToTopButton from "@/components/ScrollToTopButton";
import Head from "next/head";
import SecondNavbar from "@/components/SecondNavBar";

interface Release {
  title: string;
  date: string;
  cover: string;
  href: string;
}

export default function ZecaIcaris() {
  const [showScrollTop, setShowScrollTop] = useState(false);
  const sectionsRef = useRef<HTMLDivElement[]>([]);

  const releases: Release[] = [
    {
      title: "Zeca Icaris - Parasita",
      date: "Released October 16, 2023",
      cover: "/assets/covers/zecaParasita.png",
      href: "https://www.youtube.com/playlist?list=PLFWypV3Onhh5HNVEm_8Syq-y9qXjXAuna",
    },
  ];

  // === Fade-in for Banner ===
  useEffect(() => {
    const banner = document.querySelector<HTMLDivElement>(`.${styles.bannerImage}`);
    if (banner) {
      banner.style.opacity = "1";
      banner.style.transform = "scale(1)";
    }
  }, []);

  // === Scroll-to-top Button Visibility ===
  useEffect(() => {
    const handleScroll = () => {
      setShowScrollTop(window.scrollY > 300);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  // === IntersectionObserver for Section Animations ===
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add(styles.fadeInSection);
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.15 }
    );

    sectionsRef.current.forEach((section) => {
      if (section) {
        observer.observe(section);
      }
    });

    return () => observer.disconnect();
  }, []);

  // === Assign Refs to Sections Dynamically ===
  const setSectionRef = (el: HTMLElement | null, index: number) => {
    if (el instanceof HTMLDivElement) {
      sectionsRef.current[index] = el;
    }
  };

  // === Smooth Scroll to Top ===
  const scrollToTop = () => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <div className={styles.artistPage}>
      <Head>
        <title>Zeca Icaris | KyotoRecords</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/d-kyoto-cherry.ico"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="icon"
          href="/w-kyoto-cherry.ico"
          media="(prefers-color-scheme: dark)"
        />
      </Head>
      <Header />
      <SecondNavbar />

      {/* Banner */}
      <div className={styles.banner}>
        <div className={styles.bannerImage}></div>
        <div className={styles.bannerContent}>
          <a href="https://wottiem.vercel.app" target="_blank">
            <img
              src="/assets/ZecaIcaris.png"
              className={styles.zecaTitle}
              alt="Logo de Zeca Icaris"
              draggable="false"
            />
          </a>
          <p>
            Zeca Icaris é um músico visionário de Recife que mistura soul, R&B e experimentalismo.
            Com uma sonoridade envolvente e letras que exploram sentimentos profundos, Zeca cria músicas que tocam a alma.
            Sua jornada musical começou em 2020, em meio à pandemia, como forma de expressão durante um período desafiador.
          </p>
        </div>
      </div>

      {/* Principais Lançamentos */}
      <ReleasesSection
        releases={releases}
        setSectionRef={setSectionRef}
        sectionIndex={0}
      />

      {/* Social Links */}
      <section ref={(el) => setSectionRef(el, 1)} className={styles.socialLinks}>
        <h2>Conecte-se</h2>
        <div className={styles.links}>
          <a
            href="https://www.instagram.com/zecaicaris"
            target="_blank"
            rel="noopener noreferrer"
          >
            Instagram
          </a>
          <a
            href="https://open.spotify.com/playlist/4pomryuY2J4dgsrYycJqul?si=d3da71d0f876436e"
            target="_blank"
            rel="noopener noreferrer"
          >
            Spotify
          </a>
          <a
            href="https://www.youtube.com/@kyoto.records"
            target="_blank"
            rel="noopener noreferrer"
          >
            YouTube
          </a>
        </div>
      </section>

      <Footer />

      <ScrollToTopButton />
    </div>
  );
}
