import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import ContentMusicArtist from "@/components/home/ContentMusicArtist";
import Footer from "@/components/Footer";
import ScrollToTopButton from "@/components/ScrollToTopButton";
import SecondNavbar from "@/components/SecondNavBar";

export default function Home() {
  return (
    <>
      <Head>
        <title>KyotoRecords</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/d-kyoto-cherry.ico"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="icon"
          href="/w-kyoto-cherry.ico"
          media="(prefers-color-scheme: dark)"
        />
      </Head>
      <Header />
      <SecondNavbar />
      <main className={styles.mainHomePage}>
        <div className={styles.titleReleased}>
          ÚLTIMOS LANÇAMENTOS
        </div>
        <ContentMusicArtist />

      </main>
      <Footer />
      <ScrollToTopButton />
    </>
  );
}
