import React from "react";
import styles from "@/styles/Videos.module.css";
import Header from "@/components/Header";
import SecondNavBar from "@/components/SecondNavBar";
import Head from "next/head";
import Footer from "@/components/Footer";

const videos = [
  "https://www.youtube.com/embed/onrYIcCrokA",
  "https://www.youtube.com/embed/TxX9ZMVu6us",
  "https://www.youtube.com/embed/JlSjYk8AJqY",
];

const VideoGallery: React.FC = () => {
  return (
    <>  
      <Head>
        <title>Vídeos | KyotoRecords</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="/d-kyoto-cherry.ico"
          media="(prefers-color-scheme: light)"
        />
        <link
          rel="icon"
          href="/w-kyoto-cherry.ico"
          media="(prefers-color-scheme: dark)"
        />
      </Head>
      <Header />
      <SecondNavBar />

      <section className={styles.sectionVideos}>
        <div className={styles.galleryContainer}>
          {videos.map((video, index) => (
            <div key={index} className={styles.galleryItem}>
              <iframe
                className={styles.videoIframe}
                src={video}
                title={`Vídeo ${index + 1}`}
                frameBorder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              ></iframe>
            </div>
          ))}
        </div>
      </section>

      <Footer />
    </>
  );
};

export default VideoGallery;
